# Numpy ufunc functions

Numpy ufunc functions are built-in numpy functions that perform operations on ndarrays element-by-element.

It supports several standard features such as array broadcasting and type casting. It can also be described as a wrapper class for functions taking inputs and producing outputs of specific number.

In [35]:
import numpy as np

## Arithmetic

In [6]:
# Addition
np_a1 = np.arange(5*5).reshape(5,5)
np_a1 + 3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [10]:
# Subtraction
np_a1 = np.arange(6*6).reshape(6,6)
np_a1 - 4

array([[-4, -3, -2, -1,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [25]:
# Multiplication
np_a1 = np.arange(2*2).reshape(-1)
np_a1*2

array([0, 2, 4, 6])

In [26]:
# Division
np_a1 = np.arange(3*3).reshape(-1)
np_a1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [27]:
# Power
np_a1 = np.arange(3*3).reshape(9)
np_a1**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512], dtype=int32)

In [34]:
# Floor Division
np_a1 = np.arange(10*10).reshape(10*10)
np_a1//5

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10,
       10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13,
       13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16,
       17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19],
      dtype=int32)

## Trignometric

In [54]:
angles = np.arange(0,361,30)

In [55]:
radians = np.deg2rad(angles)
radians

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653, 6.28318531])

In [41]:
np.sin(radians)

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  5.00000000e-01,  1.22464680e-16, -5.00000000e-01,
       -8.66025404e-01, -1.00000000e+00, -8.66025404e-01, -5.00000000e-01,
       -2.44929360e-16])

In [42]:
np.cos(radians)

array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -8.66025404e-01, -1.00000000e+00, -8.66025404e-01,
       -5.00000000e-01, -1.83697020e-16,  5.00000000e-01,  8.66025404e-01,
        1.00000000e+00])

In [43]:
np.tan(radians)

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16,  5.77350269e-01,
        1.73205081e+00,  5.44374645e+15, -1.73205081e+00, -5.77350269e-01,
       -2.44929360e-16])

In [44]:
np.sinh(radians)

array([  0.        ,   0.54785347,   1.24936705,   2.3012989 ,
         3.99869134,   6.8176233 ,  11.54873936,  19.51900705,
        32.96390029,  55.6543976 ,  93.95465347, 158.60699506,
       267.74489404])

In [45]:
np.cosh(radians)

array([  1.        ,   1.14023832,   1.60028686,   2.50917848,
         4.12183605,   6.89057236,  11.59195328,  19.54460632,
        32.97906491,  55.66338089,  93.95997503, 158.61014747,
       267.74676148])

In [46]:
np.tanh(radians)

array([0.        , 0.48047278, 0.78071444, 0.91715234, 0.97012382,
       0.98941321, 0.99627208, 0.99869021, 0.99954017, 0.99983861,
       0.99994336, 0.99998012, 0.99999303])

In [47]:
np.arcsin(radians)

C:\Users\Faraz\AppData\Local\Temp\ipykernel_4604\4042167314.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(radians)


array([0.        , 0.55106958,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan])

In [48]:
np.arccos(radians)

C:\Users\Faraz\AppData\Local\Temp\ipykernel_4604\194661201.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(radians)


array([1.57079633, 1.01972674,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan])

In [49]:
np.arctan(radians)

array([0.        , 0.48234791, 0.80844879, 1.00388482, 1.12533883,
       1.20592739, 1.26262726, 1.30444211, 1.33645024, 1.36169168,
       1.38208297, 1.3988865 , 1.41296514])

In [50]:
np.arcsinh(radians)

array([0.        , 0.50221899, 0.91435666, 1.23340312, 1.48507048,
       1.69018317, 1.86229574, 2.01013875, 2.13951221, 2.25441459,
       2.35769933, 2.45146536, 2.5372975 ])

In [51]:
np.arccosh(radians)

C:\Users\Faraz\AppData\Local\Temp\ipykernel_4604\3618060095.py:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(radians)


array([       nan,        nan, 0.30604211, 1.02322748, 1.36981867,
       1.61690509, 1.81152627, 1.97287564, 2.11099631, 2.23188925,
       2.33945646, 2.43638993, 2.52463066])

In [52]:
np.arctanh(radians)

C:\Users\Faraz\AppData\Local\Temp\ipykernel_4604\899475409.py:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(radians)


array([0.        , 0.58128501,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan])

In [53]:
np.rad2deg(radians)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330., 360.])

## Statistics

In [57]:
randoms = np.arange(np.random.randint(10,20))

In [58]:
randoms

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [60]:
# Min value of array
np.amin(randoms)

0

In [63]:
# Max value of array
np.amax(randoms)

13

In [64]:
# Range of values (max - min)
np.ptp(randoms)

13

In [65]:
np.mean(randoms)

6.5

In [66]:
np.median(randoms)

6.5

In [67]:
# Standard deviation of array
np.std(randoms)

4.031128874149275

In [68]:
# Variance of array
np.var(randoms)

16.25